### ISSUE TITLE
I got problem with CLIENT_ID and CLIENT_SECRET.

### ISSUE THREAD

**Issue by maryampashmi** [Awk34/aksite#1]
Hi,

I couldn't solve this issue https://github.com/DaftMonk/generator-angular-fullstack/issues/942#issuecomment-95194578 , i still have the same problem and i couldn't solve that. 

I will be appreciated for your help.

Thank you .

**Comment by Awk34** [comment]
[solved](https://stackoverflow.com/questions/29973606/error-redirect-uri-mismatch-in-google-oauth-angularjs-full-stack-generator)
