### ISSUE TITLE
Admin / auth required

### ISSUE THREAD

**Issue by snormand** [Awk34/aksite#3]
Hi,

I know that it's now an issue, but I would like to know where you tell the angular App that the "/admin" section requires authentication?

Thanks for the information!!

Simon

**Comment by Awk34** [comment]
Right now I'm not requiring a person to be logged into an admin account to visit `/admin`. If you try it, you'll probably be able to see a quick flash of it. The reason that it redirects back to the login page is that once you go to `/admin`, I make a few API calls that require admin privileges. Any unauthorized calls to the API result in a redirect to the login page. This is done [here](https://github.com/Awk34/aksite/blob/master/client/app/app.js#L37).

**Comment by Awk34** [comment]
This website is based off of the [Angular Full-stack Generator](https://github.com/DaftMonk/generator-angular-fullstack). [This](https://github.com/DaftMonk/generator-angular-fullstack/blob/master/app/templates/client/app/app(js).js#L50) is how we have solved the issue there.
