### ISSUE TITLE
Need to update the Readme.MD?

### ISSUE THREAD

**Issue by lukeqi** [Awk34/aksite#6]
Haha, want to test out this project.

**Comment by Awk34** [comment]
Did you get an error? One thing I noticed I haven't changed: replace Grunt with Gulp.

**Comment by lukeqi** [comment]
Thank you! Got an error when using node 0.12 (the same as I use for the yeoman angular fullstack generator) and get error, I will try node 4.2.2 as your ReadME suggests.

**Comment by lukeqi** [comment]
Hi Awk, 
I use with node 4.2.2 with npm 3.5.0.However, after npm install and bower install, when I run gulp serve, I got:

```
[04:00:42] Finished 'wiredep:client' after 2.62 ms
[04:00:43] gulp-inject Nothing to inject into index.html.

client/app/app.js
  line 77  col 13  Bad line breaking before '+'.
  line 78  col 17  Bad line breaking before '?'.
  line 80  col 13  Bad line breaking before '+'.
  line 81  col 13  Bad line breaking before '+'.
  line 82  col 13  Bad line breaking before '+'.

✖ 5 problems
```

It seems something went wrong.

**Comment by Awk34** [comment]
Those are just JSHint errors that I haven't gotten around to fixing yet.
You can ignore them.
