### ISSUE TITLE
About the comments part of the posts

### ISSUE THREAD

**Issue by lukeqi** [Awk34/aksite#7]
This webapp is beautiful and it is an enhancement of the example project of the Yeoman-Angular-Fullstack generator!

If I do not put it wrong, this app implements the "comments" part of the "posts" with some suite from "https://disqus.com". 

As I test the comments function I find it very easy to use and very smooth, and I am amazed by it. I just want to make sure that the comments system is not implemented within this project, as I decide to write a comments system by myself based on the generator.

**Comment by Awk34** [comment]
Yeah, I felt like it would be better to implement Disqus for comments since it has a lot of popularity elsewhere. It is familiar and easy to use, especially since plenty of people have use Disqus before and already have an account with them.

**Comment by lukeqi** [comment]
Ok, got it!
