### ISSUE TITLE
When uploading a file, how do you get the file.id?

### ISSUE THREAD

**Issue by skywalkerlucas** [Awk34/aksite#86]
I read through your code, and I have a question:

In projectEditor, galleryEditor, I select a file to upload, 

and then in server side, we get the file.id ( which is similar to a mongo Object id), 

I am wondering how the file.id is attached to the file?

As we submit a file from the browser, I could see no where to give the file the "id" attribute.

It is a very complete project. Thanks a lot!

**Comment by Awk34** [comment]
[gridform](https://github.com/aheckmann/gridform) does that: https://github.com/Awk34/aksite/blob/master/server/api/post/post.controller.js#L83 . It uses [formidable](https://github.com/felixge/node-formidable) and Mongo's GridFS.

gridform will take the file from the request and stream it into GridFS. Once that's done, it will return the Mongo document for that file. That's where the `file.id` comes from. The ID is generated by Mongo, you can't set it from the client-side.

**Comment by skywalkerlucas** [comment]
Hey @Awk34 ,

Your answer is very clear, thank you a lot !!

By the way, I checked gridform and gridfs-stream packages, and have found that they have not so much stars, it seems that they are not so popular.

However, they are the only modules that I can find in the internet that are customized for uploading files to interact with Mongo's GridFS in node.

I do not know why they are not popular, is it because there too few people using node with mongodb?

Or because thier APIs are too intimidating? When I first saw the code and your code in the create method of an backend api, it looks so complicated and "intimidating".

We use node and mongodb to be more easily manipulate things, but those APIs mentioned above seems intimidating.

As now I do not intend to save a file which is larger than 16 MB into the my mongodb, now I just save Binary files directly in one doc in mongodb, and it is find at the moment.

But I want to ask, is there some simpler modules/APIs for us to interact with Mongo's GridFS?

Lastly, your project is very compelete and helps me very much in my road of learning front-end development (although I intend to use React in the front), thank you so much. I wish this project have more stars

**Comment by Awk34** [comment]
In respect to gridfrom and gridfs-stream, I'm not sure why they don't get more attention :confused: ; and I do kind of agree that looking at it for the first time can be a bit much, but this setup worked for me, and I found it to be performant. There might be other good alternatives that I don't know of. 

While I don't often save files larger than 16MB into Mongo, it feels dirty to try to smash a binary image file (that's what I mainly use it for) into a Mongo document, although a small Base64 encoded image wouldn't hurt.

I'm glad that my little project here has helped you :smile: .

**Comment by skywalkerlucas** [comment]
@Awk34  Thanks :smiley:
